CREATE TABLE
    users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(127) NULL DEFAULT NULL,
        email VARCHAR(127) NOT NULL UNIQUE,
        email_verified_at TIMESTAMP NULL DEFAULT NULL,
        password VARCHAR(255) NULL DEFAULT NULL,
        role_id INT (7) NULL DEFAULT NULL,
        api_token VARCHAR(255) NULL DEFAULT NULL,
        status_id INT (7) NULL DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE
    roles (
        id INT (7) NULL DEFAULT NULL,
        role VARCHAR(127) NULL DEFAULT NULL,
        status_id INT (7) NULL DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );