CREATE TABLE
    users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(127) NULL DEFAULT NULL,
        email VARCHAR(127) NOT NULL UNIQUE,
        email_verified_at TIMESTAMP NULL DEFAULT NULL,
        password VARCHAR(255) NULL DEFAULT NULL,
        role_id INT NULL DEFAULT NULL,
        api_token VARCHAR(255) NULL DEFAULT NULL,
        status_id INT NULL DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE
    roles (
        id INT AUTO_INCREMENT PRIMARY KEY,
        role VARCHAR(127) NULL DEFAULT NULL,
        status_id INT NULL DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE
    user_profiles (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        country_code VARCHAR(8) NULL DEFAULT NULL,
        contact VARCHAR(16) NULL DEFAULT NULL,
        status_id INT NULL DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        CONSTRAINT fk_userprofile_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE
    statuses (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(127) NULL DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE
    shops (
        id INT AUTO_INCREMENT PRIMARY KEY,
        owner_id INT NOT NULL,
        name VARCHAR(127) NULL DEFAULT NULL,
        email VARCHAR(127) NULL DEFAULT NULL,
        token VARCHAR(255) NULL DEFAULT NULL,
        address VARCHAR(255) NULL DEFAULT NULL,
        city VARCHAR(255) NULL DEFAULT NULL,
        district VARCHAR(255) NULL DEFAULT NULL,
        country VARCHAR(255) NULL DEFAULT NULL,
        status_id INT NULL DEFAULT NULL,
        creator_id INT NULL DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE
    user_management_shops (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        shop_id INT NOT NULL,
        token VARCHAR(255) NULL DEFAULT NULL,
        status_id INT NULL DEFAULT NULL,
        creator_id INT NULL DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE
    shop_items (
        id INT AUTO_INCREMENT PRIMARY KEY,
        shop_id INT NOT NULL,
        name VARCHAR(127) NULL DEFAULT NULL,
        unit_type enum ('kg', 'l', 'piece') NULL DEFAULT NULL,
        description VARCHAR(255) NULL DEFAULT NULL,
        price DECIMAL(10, 2) NULL DEFAULT NULL,
        qty INT NULL DEFAULT NULL,
        status_id INT NULL DEFAULT NULL,
        creator_id INT NULL DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );